name: Release (Prod)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript and bundle into asar
        run: pnpm run build:prod:bundle

      - uses: ncipollo/release-action@main
        with:
          artifacts: 'bundle/*'
          makeLatest: true
